version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "customer-inquiry-manager"
          ContainerPort: 8000
        CapacityProviderStrategy:
          - CapacityProvider: "FARGATE"
            Weight: 1
            Base: 1
          - CapacityProvider: "FARGATE_SPOT"
            Weight: 3
            Base: 0
